### ISSUE TITLE
Проверка лабораторной работы 2 задание 1

### ISSUE THREAD

**Issue by dragoblued** [dragoblued/lab_2_1#1]
Работу выполнила:
Табаева Н.А.

To: @evgeny-p

**Comment by evgeny-p** [comment]
Выполнена только одна часть первого задания: разрешение конфликта.
Нужно выполнить оставшуюся: мерж ветки с ключом `--no-ff`. Ожидаемая топология истории репозитория изображена на [слайде 37](http://evgeny-p.github.io/teaching/materials/week-02/slides/#37). Порядок выполнения заданий (разрешение конфликта и мерж с `--no-ff`) значения не имеет.
